# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_data": "01_widgets.ipynb",
         "get_hkont_options": "01_widgets.ipynb",
         "get_data": "01_widgets.ipynb",
         "info_widget_children": "01_widgets.ipynb",
         "get_infos": "01_widgets.ipynb",
         "new_infos_widget": "01_widgets.ipynb",
         "update_infos_widget": "01_widgets.ipynb",
         "new_p1_widget": "01_widgets.ipynb",
         "update_p1_widget": "01_widgets.ipynb",
         "new_p2_widget": "01_widgets.ipynb",
         "update_p2_widget": "01_widgets.ipynb",
         "new_dataloader_widget": "01_widgets.ipynb",
         "infos_widget": "01_widgets.ipynb",
         "p1_widget": "01_widgets.ipynb",
         "p2_widget": "01_widgets.ipynb",
         "dataloader_widget": "01_widgets.ipynb"}

modules = ["widgets.py"]

doc_url = "https://jolahann.github.io/voidash/"

git_url = "https://github.com/jolahann/voidash/tree/main/"

def custom_doc_links(name): return None
